doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '15'

    #orm:
    #    auto_generate_proxy_classes: true
    #    naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
    #    auto_mapping: false
    #    mappings:
    #        DoctrineUser:
    #            is_bundle: false
    #            type: xml
    #            dir: '%kernel.project_dir%/src/User/Infrastructure/Database/ORM/Doctrine/Mapping/'
    #            prefix: 'App\User\Infrastructure\Database\ORM\Doctrine\Entity'
    #            alias: DoctrineUser
    orm:
        entity_managers:
            app:
                mappings:
                    DoctrineUser:
                        is_bundle: false
                        type: xml
                        dir: '%kernel.project_dir%/src/User/Infrastructure/Database/ORM/Doctrine/Mapping/'
                        prefix: 'App\User\Infrastructure\Database\ORM\Doctrine\Entity'
                        alias: DoctrineUser

when@test:
    doctrine:
        dbal:
            # "TEST_TOKEN" is typically set by ParaTest
            dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            proxy_dir: '%kernel.build_dir%/doctrine/orm/Proxies'
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
